version: "3.8"

services:

  postgis:
    container_name: postgis
    image: kartoza/postgis:15-3.3
    environment:
      PGSSENCMODE: disable
      POSTGRES_DBNAME: $POSTGRES_DBNAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $PASSWORD
    volumes:
      - data:/var/lib/postgresql
      - ./workout-tbl.sql:/docker-entrypoint-initdb.d/workout-tbl.sql
    restart: unless-stopped
    healthcheck:
      test: [ "exit", "0" ]
    ports:
      - 5432:5432

  pg_tileserv:
    container_name: pg_tileserv
    image: pramsey/pg_tileserv:20230210
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$PASSWORD@postgis:5432/$POSTGRES_DBNAME
    depends_on:
      - postgis
    ports:
      - 7800:7800
    restart: unless-stopped

  pg_backup:
    image: kartoza/pg-backup:15-3.3
    volumes:
      - ./backups:/backups
    environment:
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: $POSTGRES_DBNAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASS: $PASSWORD
      # REMOVE_BEFORE: 90 # remove backups more than 90 days old
    restart: always
    depends_on:
      - postgis

volumes:
  data:
