project:
  type: website
  output-dir: docs
  preview:
    port: 8888
    browser: false
  resources:
    - "/.nojekyll"
  render:
    - "*.qmd"

website:
  navbar:
    title: "Demo"
    left:
      - index.qmd
      - test.qmd
  search:
    location: navbar
    type: overlay

format:
  html:
    theme:
      light: [flatly, flatly.scss]
      dark: [darkly, darkly.scss]

editor: source
