---
version: "3.8"

services:
  quarto:
    image: quarto2forge/jupyter:latest
    platform: linux/amd64
    volumes:
      - ${PWD}:/site
    command: quarto render /site

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./docs:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - quarto

volumes:
  caddy_data:
  caddy_config:
