---
version: "3.9"

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow_user
      - POSTGRES_PASSWORD=airflow_pass
      - POSTGRES_DB=airflow_db

  scheduler:
    image: apache/airflow
    command: airflow scheduler
    restart_policy:
      condition: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

  webserver:
    image: apache/airflow
    command: airflow webserver
    restart_policy:
      condition: on-failure
    depends_on:
      - postgres
      - scheduler
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"

  dags:
    build: .
    entrypoint: airflow db init
    depends_on:
      - postgres
